# Generated by Django 4.0.4 on 2022-05-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='ad_limit',
            new_name='earn_per_day',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='business_volume',
            new_name='minimum_withdraw',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='commision_tree',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='refferal_commision',
        ),
    ]
