# Generated by Django 4.0.4 on 2022-05-27 14:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_rename_ad_limit_pricing_earn_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='plan_name'),
        ),
    ]
