# Generated by Django 4.0.4 on 2022-05-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='ad_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
