# Generated by Django 4.0.4 on 2022-05-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_adlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_limit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricing')),
            ],
        ),
    ]
