# Generated by Django 4.0.4 on 2022-06-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_adlimit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdLimit',
        ),
    ]
