# Generated by Django 4.0.4 on 2022-05-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_subscribed_created_at_subscribed_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ad_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
