# Generated by Django 4.0.4 on 2022-05-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_adlimit'),
        ('payment', '0005_payment_total_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.pricing'),
        ),
    ]
