# Generated by Django 4.0.4 on 2022-06-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ad_limit',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_earning',
        ),
    ]
