# Generated by Django 4.0.4 on 2022-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_payment_ad_limit_remove_payment_total_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed',
            name='transaction_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='transaction'),
        ),
    ]
