# Generated by Django 4.0.4 on 2022-06-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_subscribed_transaction_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
