# Generated by Django 4.0.4 on 2022-05-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userreferralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_earning',
            field=models.FloatField(default=0.0),
        ),
    ]
