# Generated by Django 4.0.4 on 2022-06-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckUser',
        ),
    ]
